---
stages:
  - displayName: Build the web application
    jobs:
      - displayName: Build job
        job: Build
        pool:
          demands:
            - npm
          vmImage: ubuntu-20.04
    stage: Build
steps:
  - displayName: Use .NET SDK $(dotnetSdkVersion)
    inputs:
      version: $(dotnetSdkVersion)
    task: UseDotNet@2
  - displayName: Run npm install
    inputs:
      verbose: false
    task: Npm@1
  - displayName: Compile Sass assets
    script: ./node_modules/.bin/node-sass $(wwwrootDir) --output $(wwwrootDir)
  - displayName: Run gulp tasks
    task: gulp@1
  - displayName: Write build info
    script: echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" >  buildinfo.txt
    workingDirectory: $(wwwrootDir)
  - displayName: Restore project dependencies
    inputs:
      command: restore
      projects: '**/*.csproj'
    task: DotNetCoreCLI@2
  - displayName: Build the project - $(buildConfiguration)
    inputs:
      arguments: '--no-restore --configuration $(buildConfiguration)'
      command: build
      projects: '**/*.csproj'
    task: DotNetCoreCLI@2
  - displayName: Publish the project - $(buildConfiguration)
    inputs:
      arguments: '--no-build --configuration $(buildConfiguration) --output  $(Build.ArtifactStagingDirectory)/$(buildConfiguration)'
      command: publish
      projects: '**/*.csproj'
      publishWebProjects: false
      zipAfterPublish: true
    task: DotNetCoreCLI@2
  - artifact: drop
    publish: $(Build.ArtifactStagingDirectory)
trigger:
  - '*'
variables:
  buildConfiguration: Release
  dotnetSdkVersion: 5.x
  wwwrootDir: Tailspin.SpaceGame.Web/wwwroot